import { fileURLToPath } from 'node:url';

import react from '@vitejs/plugin-react';
import { defineConfig } from 'vitest/config';

/**
 * The component suite runs in jsdom against a hand-written `fetch` fake — the
 * same convention the API suite follows, where test doubles implement the port
 * rather than being generated by a mocking framework. `src/test/fake-api.ts` is
 * a small in-memory API: it routes on the contract's own `ROUTES` table and
 * answers in the contract's envelopes, so a test that passes against it is a
 * test that agreed with the wire contract.
 */
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  test: {
    include: ['src/**/*.test.ts', 'src/**/*.test.tsx'],
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    restoreMocks: true,
    // Must exceed `asyncUtilTimeout` in vitest.setup.ts. At the default 5000 the
    // two are equal, so a `findBy*` that never resolves kills the test before
    // Testing Library can report *what* it was looking for — every real failure
    // arrives as a bare "Test timed out" instead of a query and a DOM dump.
    testTimeout: 15_000,
    // `installFakeApi` stubs `globalThis.fetch`; this puts the real one back
    // between tests so a suite cannot leak a fake into the next one.
    unstubGlobals: true,
  },
});
