/**
 * Source of unique identifiers.
 *
 * Identity is generated by the application, not by the datastore. That keeps
 * the aggregate fully formed before it is ever persisted, and means switching
 * from an in-memory Map to a database never requires a round trip just to
 * learn what the entity's own id is.
 */
export interface IdGenerator {
  generate(): string;
}
